server:
  port: 8083

spring:
  application:
    name: quiz-communication

  threads:
    virtual:
      enabled: true

  config:
    import:
      - optional:file:./config/  # Override to disable Nacos import

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    stream:
      enabled: false

  autoconfigure:
    exclude:
      - org.springframework.cloud.stream.config.BindingServiceAutoConfiguration
      - org.springframework.cloud.stream.config.BinderFactoryAutoConfiguration

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.t3a.communication: DEBUG
